version '3.8':
  services:
    #   api:
    #     build: packages/api
    site:
      build: packages/site/
      depends_on:
        - api
#   storybook:
#     build: packages/storybook
#     depends_on:
#       - api