# ToDo: How view container ip after build?

version: '3.5'
services:
# api:
#   build: packages/api
  site:
    build:
      context: ./
      dockerfile: ./packages/site/Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
#    depends_on:
#      - api
# storybook:
#   build: packages/storybook
#   depends_on:
#     - api
