version: '3.5'

volumes:
  web_build:

services:

  # api:
  #   build: packages/api
  #   depends_on:

  web:
    build:
      context: ./
      dockerfile: ./packages/web/Dockerfile
    #    depends_on:
    #      - api
    expose:
      - "${WEB_PORT}"
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    volumes:
      - type: tmpfs
        source: web_build
        target: /app/packages/web/build:rw

  # storybook:
  #   build: packages/storybook
  #   depends_on:
  #     - api

  nginx:
    build:
      context: ./
      dockerfile: ./config/nginx/Dockerfile
    expose:
      - "${NGINX_PORT}"
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - web
    volumes:
      - web_build:/app/packages/web_build:ro