name: Deploy
on:
  push:
    branches: 
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name:  "ls"
        run: ls
      - name: "Connect to server"
        run: "ssh -i /settings/secrets/SSHKEY ${{ secrets.USERNAME }}@${{ secrets.HOST }}:${{ secrets.PORT }}"
      - name:  "ls"
        run: ls
