name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy_prod:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: "Build and Up"
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: |
            cd ${{ secrets.WORKDIR }}
            git reset --hard HEAD
            git checkout master
            git pull
            docker-compose down
            docker-compose up --build --force-recreate --no-deps -d -V --remove-orphans